export interface ActionType {
    type: string;
    payload: any;
}

export const ADD_GOVERMENT_PROJECT = 'ADD_GOVERMENT_PROJECT';
export const ADD_FEDERAL_PROJECT_TAB = 'ADD_FEDERAL_PROJECT_TAB';
export const SET_SPECIFIC_STRUCTURAL_ELEMENT = 'SET_SPECIFIC_STRUCTURAL_ELEMENT';
export const SET_SPECIFIC_DEPARTMENTAL_PROJECT = 'SET_SPECIFIC_DEPARTMENTAL_PROJECT';

export const CLEAR_ALL_FIELDS = 'CLEAR_ALL_FIELDS';
